# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GYITXcWhk6J6T_QPiK_4PP-XlwM69Pq
"""

st.dataframe(filtered)

# Graph
fig = px.scatter(df, x='GDP', y='CO2 Emissions',
                 color=df['Cluster'].astype(str),
                 hover_name='Country')

st.plotly_chart(fig)

# Prediction
st.subheader("Predict Cluster")

gdp = st.number_input("GDP")
birth = st.number_input("Birth Rate")
co2 = st.number_input("CO2 Emissions")

if st.button("Predict"):
    data = np.array([[gdp, birth, co2]])
    scaled = scaler.transform(data)
    pred = model.predict(scaled)
    st.success(f"Cluster: {pred[0]}")